language: php
script:
  - echo "Nothing to do!"
services:
- docker
env:
  global:
  - DOCKER_USER=alimohammadi340
  - COMMIT=${TRAVIS_COMMIT::8}
after_success:
- docker login quay.io -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=quay.io/alimohammadi340/php-logger
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker image ls
- docker push $REPO
